cea-hpc/NabLab

fr.cea.nabla.ui/META-INF/MANIFEST.MF
fr.cea.nabla.ui/build.properties
fr.cea.nabla.ui/plugin.properties
fr.cea.nabla.ui/plugin.xml
fr.cea.nabla.ui/src/fr/cea/nabla/ui/perspectives/NabLabPerspective.xtend
fr.cea.nabla.ui/src/fr/cea/nabla/ui/wizards/NablaProjectPage.xtend
fr.cea.nabla.ui/src/fr/cea/nabla/ui/wizards/NewNablaProjectWizard.xtend

- Add new wizard to create a nabla project (modeling, java, xtext,
plugin project) with default nabla and nablagen models
- Update perspective to display new wizard in File > New menu
Change-Id: I546d9fffe653820df67767ca94472399c818bd46

New Nabla Project Wizard

---

plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/generator/java/ExpressionContentProvider.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/generator/kokkos/ExpressionContentProvider.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/BinaryOperationsInterpreter.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/Context.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/ExpressionInterpreter.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/InstructionInterpreter.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/JobInterpreter.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/ModuleInterpreter.xtend
plugins/fr.cea.nabla.javalib/src/fr/cea/nabla/javalib/mesh/CartesianMesh2D.xtend

A set of changes to further optimize the Nabla interpreter, including:
- use of additional maps to cache effectively constant values
- some refactorings of the Xtend code to improve the quality of the generated Java code

Optimizing interpreter

---

plugins/fr.cea.nabla/META-INF/MANIFEST.MF
plugins/fr.cea.nabla/pom.xml

Change-Id: I03c583c8efd390630b8f6291ee3494b61faa841d

Fix maven build for 2020-03

---

tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/AbstractBinaryOperationsInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/AbstractExpressionInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/AbstractInstructionInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/AbstractJobInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/AbstractModuleInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/BinaryOperationsInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/ExpressionInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/InstructionInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/JobInterpreterTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/NabLabInterpreterTestSuite.java

Introduces abstract test classes factorizing code needed to for all NabLab interpreters.

Abstract interpreter test case

---

HowToGitNabLab.md

Et ça permet de test le pull-request ;)

Markdown guide to git for NabLab project

---

plugins/fr.cea.nabla/src/fr/cea/nabla/validation/InstructionValidator.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/validation/InstructionValidatorTest.xtend

Add a new validator to avoid direct affectation between connectivity Variables

Affectations

---

plugins/fr.cea.nabla.ui/plugin.xml

This adds the launch action set to the NabLab perspective.

Launch Action Set

---

plugins/fr.cea.nabla.ui/META-INF/MANIFEST.MF
plugins/fr.cea.nabla.ui/src/fr/cea/nabla/ui/console/NabLabConsole.xtend
plugins/fr.cea.nabla.ui/src/fr/cea/nabla/ui/console/NabLabConsoleActions.xtend
plugins/fr.cea.nabla.ui/src/fr/cea/nabla/ui/console/NabLabConsoleFactory.xtend
plugins/fr.cea.nabla.ui/src/fr/cea/nabla/ui/console/NabLabConsoleRunnable.xtend
plugins/fr.cea.nabla.ui/src/fr/cea/nabla/ui/launchconfig/NablagenRunner.xtend

- Add fr.cea.nabla.ui.console to exported package of fr.cea.nabla.ui
- Stop button now executes runnable provided by nablagen runner

Stop button refactoring

---

plugins/fr.cea.nabla.ir/META-INF/MANIFEST.MF
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/ExtensionProviderExtensions.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/ExtensionProviderCache.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/interpreter/ExtensionProviderHelper.xtend
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/transformers/ReplaceAffectations.xtend

Correct loop generation for affectations on connectivity variables for connectivities with arg
Correct bug on interpreter for erf function

Corrections for eucllhyd Code

---

.github/workflows/build.yml
pom.xml
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/NabLabTestSuite.java
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/interpreter/NabLabInterpreterTestSuite.java

- Add a new profile to maven build : the pom file now contains two profiles named "build" and "updatesite", the first one for the compilation and tests, the second one for the features, updatsite and products
- Create a new workflow named build.yml : this workflow executes import.sh script and maven "build" profile on every push and pull request. Also executes the "updatesite" profile when a tag starting with 'v' is created.

Add Github Action for NabLab

---

docs/fr.cea.nabla.mkdocs/docs/gettingstarted.md

Change-Id: I00edbfdd92f66596f91c820fb5b621b276dd7eef

Doc - Update doc with the new maven profile

---

.github/workflows/build.yml

- Remove Java Setup
- Release step is now draft release

GithubActions - Update build.yml

---

.github/workflows/build.yml
docs/fr.cea.nabla.mkdocs/docs/docker.md
docs/fr.cea.nabla.mkdocs/docs/docker/docker-nablab.sh
docs/fr.cea.nabla.mkdocs/mkdocs.yml
tests/fr.cea.nabla.tests/META-INF/MANIFEST.MF
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/NabLabTestSuite.java
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/NablaExamplesTest.xtend

This public container hosted on Docker Hub (nablab/execution-env) enables to execute GitHub actions Continuous integration.
It is a ubuntu container + level_db + kokkos
NB: any error in the execution of glace2D kokkos-team is ignored due to numerical differences (non-reproducible execution)

Use nablab docker for continuous integration

---

.github/workflows/build.yml
pom.xml
settings.xml

Release NabLab jars on https://maven.pkg.github.com/cea-hpc/NabLab

GithubActions - Deploy artifacts on mvn.pkg.github

---

docs/fr.cea.nabla.mkdocs/docs/firstmodule.md
docs/fr.cea.nabla.mkdocs/docs/nablablanguage.md

There was a few broken links in the documentation, fixed them.

Fix a few broken links in documentation

---

tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/GeneralPurposeTest.xtend

Change-Id: I9d4111695ae74af08ee5a6b61c9edec86f6c8a27

[fix] Do not check copyrights on maven polyglot files

---

README.md

Add hamcrest install information and commit message rules

[doc] Complete Guidelines for NabLab contributors

---

plugins/fr.cea.nabla.siriusweb.application/src/main/java/fr/cea/nablab/sirius/web/app/NabLabApplication.java
plugins/fr.cea.nabla.siriusweb.application/src/main/java/fr/cea/nablab/sirius/web/app/datafetchers/mutations/EditLabelEventHandler.java
plugins/fr.cea.nabla.siriusweb.application/src/main/java/fr/cea/nablab/sirius/web/app/datafetchers/mutations/MutationEditLabelDataFetcher.java

[fix] Forbid diagram elements label edition in VSCode extension

---

plugins/fr.cea.nabla.cpplib/src/mesh/cartesianmesh2darcane/CartesianMesh2D.cc
plugins/fr.cea.nabla.cpplib/src/mesh/cartesianmesh2darcane/CartesianMesh2D.h
plugins/fr.cea.nabla.ir/src/fr/cea/nabla/ir/generator/arcane/TypeContentProvider.xtend
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/accelerator/implicitheatequation/ImplicitHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/sequential/explicitheatequation/ExplicitHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/sequential/implicitheatequation/ImplicitHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/sequential/iterativeheatequation/IterativeHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/thread/explicitheatequation/ExplicitHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/thread/implicitheatequation/ImplicitHeatEquationModule.cc
plugins/fr.cea.nabla.ui/examples/NabLabExamples/src-gen-arcane/thread/iterativeheatequation/IterativeHeatEquationModule.cc

index() -> localId()
Signed-off-by: OUDOT Marie-Pierre <marie-pierre.oudot@cea.fr>

[dev] Upgrade Arcane CartesianMesh2D & generators to support MPI

---

plugins/fr.cea.nabla.ide.web/pom.xml

[releng] Bump Jetty from 10.0.6 to 10.0.11

---

tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/GenerateAndExecuteTestBase.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/NabLabExamplesTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/NabLabTestsTest.xtend
tests/fr.cea.nabla.tests/src/fr/cea/nabla/tests/ir/interpreter/NablaExamplesInterpreterTest.xtend

Use of a generic separator by using File.separator
Signed-off-by: Vincent BLAIN <vincent.blain@obeosoft.com>

[test] Fix path separator on Windows

---

plugins/fr.cea.nabla.cpplib/src/mesh/cartesianmesh2darcane/CartesianMesh2D.cc
plugins/fr.cea.nabla.cpplib/src/mesh/cartesianmesh2darcane/CartesianMesh2D.h
plugins/fr.cea.nabla.cpplib/tests/cartesianmesh2darcane/cartesian1.arc
plugins/fr.cea.nabla.cpplib/tests/cartesianmesh2darcane/main.cc

Add LeftFaces, RightFaces, Topfaces and BottomFaces definitions
This supposes that faces construction respects face numering version 4
and needs arc option <face-numbering-version>4</face-numbering-version>
Signed-off-by: OUDOT Marie-Pierre <marie-pierre.oudot@cea.fr>

[dev] add Faces groups
